spring.application.name=backend


spring.datasource.url=jdbc:postgresql://localhost:5432/insurtech
spring.datasource.username=insurtech
spring.datasource.password=insurtech

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info

server.port=8080